version: '3.8'

services:
  backend:
    build: .
    ports:
      - "2001:5000"
    environment:
      - SECRET_KEY=uma-chave-secreta-muito-segura
      - DATABASE_URL=postgresql://bwqQCwau3ybME2RR:6XHFzssSRgbjzIMUzat3i557497Zcr38@db:5433/reverse_mci
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: reverse_mci
      POSTGRES_USER: bwqQCwau3ybME2RR
      POSTGRES_PASSWORD: 6XHFzssSRgbjzIMUzat3i557497Zcr38
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: